// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyvddgoxosxjymotxyri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5dmRkZ294b3N4anltb3R4eXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTg3NDEsImV4cCI6MjA3MDA3NDc0MX0.Hsyg9T2xwLMXgv2JDFSjA0ZhPcwQKAjJyhKzYtj-XSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});